"""
__authors__: Kevin Chau, Hanqing Zhao,
__date__: 2019-03-05
__description__: RNA-Seq alignment and quantification
"""

import os

configfile: "config.yaml"

# Setup pipeline directories
if not os.path.exists("data"):
    os.makedirs("data")
if not os.path.exists("log"):
    os.makedirs("log")

rule cutadapt_trim
    input:
        config["READ1"]
        config["READ2"]
    output:
        config["OUTPUT1"]
        config["OUTPUT2"]
    shell:
        "cutadapt --minimum-length=5",
        " --output "

rule star_refIndex:
    input:
        config["GENOME_FASTA"],
        config["GENOME_GTF"]
    output:
        config["GENOME_DIR"]
    shell:
        "STAR --runThreadN 16 --runMode genomeGenerate ",
        "--genomeDir ",
        config["GENOME_DIR"],
        "--genomeFastaFiles ",
        config["GENOME_FASTA"],
        "--sjdbGTFfile ",
        config["GENOME_GTF"]

rule RSEM:
    input:
        #the output from STAR
        config["SAM/BAM"]
        config["SAMPLE_NAME"]
    output:
        config[]
    shell:
        "rsem"
