GENOME_DIR : /Users/zhq/RNAseq_Pipeline/references/
GENOME_FASTA : GRCh38.p12.genome.fa
GENOME_GTF : gencode.v30.annotation.gtf
DISK_DIR: /Users/zhq/RNAseq_Pipeline/references/STAR_INDEX

FASTQS: 
    read1: "test_reads_R1"
    read2: "test_reads_R2"
    prefix: "test_reads"
