"""
__authors__: Kevin Chau, Weixiu Dong, Hanqing Zhao
__date__: 2019-03-05
__description__: RNA-Seq alignment and quantification
"""

import os

# Sub-Workflows

subworkflow index:
    workdir: "workflows/index"
    snakefile: "workflows/index/Snakefile"  # Not required, but helpful
    configfile: "workflows/index/config.yaml"


rule run_star
    input:
        os.path.join(config["GENOME_DIR"], "STAR_INDEX", "Genome")
        os.path.join(config["GENOME_DIR"], "STAR_INDEX", "SA")
        os.path.join(config["GENOME_DIR"], "STAR_INDEX", "SAindex")
        os.path.join("../../data/",config["FASTQ_prefix"] + ".1.trimmed.fastq")
        os.path.join("../../data/",config["FASTQ_prefix"] + ".2.trimmed.fastq")
    output:
        os.path.join("../../data/STAR_ALIGN_", config["FASTQ_prefix"] + ".bam")
    shell:
        "STAR --genomeDir ", os.path.join(config["GENOME_DIR"], "STAR_INDEX"),
        " --runThreadN 12"
        " --readFilesIn ../../data/",
        " --outFilterType BySJout",
        " --outFilterMultimapNmax 20",
        " --alignSJoverhangMin 8",
        " --alignSJDBoverhangMin 1",
        " --outFilterMismatchNmax 999",
        " --alignIntronMin 20 --alignIntronMax 1000000",
        " --alignMatesGapMax 1000000 --outSAMunmapped Within",
        " --outSAMattributes NH HI AS NM MD",
        " --outFilterMismatchNoverReadLmax 0.04 --sjdbScore 1",
        " --outSAMtype BAM SortedByCoordinate --quantMode TranscriptomeSAM",
        " --outFileNamePrefix ", os.path.join(config["GENOME_DIR"], "STAR_ALIGN_")
